spring:
  datasource:
    # Configuring DataSource Drivers
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # Specify a YAML configuration file
    url: jdbc:shardingsphere:classpath:sharding.yaml

mybatis:
  mapper-locations: classpath:mappers/*xml
  configuration:
    local-cache-scope: statement