spring:
  shardingsphere:
    props.sql.show: true
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        jdbcUrl: jdbc:mariadb://127.0.0.1:3306/main
        username: root
        password: root

    sharding:
      tables:
        user:
          actual-data-nodes: ds.user_$->{1..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_$->{id % 2 + 1}
          key-generator:
            column: id
            type: SNOWFLAKE

        country_record:
          actual-data-nodes: ds.country_record_${['taiwan','china','japan','america']}
          table-strategy:
            standard:
              shardingColumn: country_id
              preciseAlgorithmClassName: com.cooba.shardingAlgorithm.CountryShardingAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
      binding-tables: user

mybatis:
  mapper-locations: classpath:mappers/*xml
  configuration:
    local-cache-scope: statement

pagehelper:
  reasonable: false
  defaultCount: true

#logging:
#  level:
#    com.cooba.mapper: debug